version: '3.8'

services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - be

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
